/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hamid
 */
public class AdminFunc extends javax.swing.JFrame {

    SavedData s=new SavedData();
    UserScreen us=new UserScreen();
    /**
     * Creates new form AdminFunc
     */
    public AdminFunc() {
        initComponents();
        Hello.setText("Hello "+ s.nameAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBook = new javax.swing.JButton();
        DeleteBook = new javax.swing.JButton();
        Req = new javax.swing.JButton();
        SwitchAdmin = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        Hello = new javax.swing.JLabel();
        Please = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Screen");

        AddBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddBook.setForeground(new java.awt.Color(0, 102, 255));
        AddBook.setText("Add a Book");
        AddBook.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });

        DeleteBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteBook.setForeground(new java.awt.Color(0, 102, 255));
        DeleteBook.setText("Delete a Book");
        DeleteBook.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookActionPerformed(evt);
            }
        });

        Req.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Req.setForeground(new java.awt.Color(0, 102, 255));
        Req.setText("Check Readers' Requests");
        Req.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Req.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReqActionPerformed(evt);
            }
        });

        SwitchAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SwitchAdmin.setText("Switch to Reader's View");
        SwitchAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitchAdminActionPerformed(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 0, 0));
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        Hello.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Hello.setForeground(new java.awt.Color(0, 51, 204));
        Hello.setText("    ");
        Hello.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Please.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        Please.setText("Select Any function");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SwitchAdmin)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(Hello, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(Please, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Req)
                            .addComponent(DeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Hello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Please, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(AddBook)
                .addGap(18, 18, 18)
                .addComponent(DeleteBook)
                .addGap(18, 18, 18)
                .addComponent(Req)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SwitchAdmin)
                    .addComponent(LogOut))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
                new AddBook().setVisible(true);
    }//GEN-LAST:event_AddBookActionPerformed

    private void DeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
                new DeleteBook().setVisible(true);
    }//GEN-LAST:event_DeleteBookActionPerformed

    private void SwitchAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitchAdminActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_SwitchAdminActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        
         s.who=false;
         us.count=0;
        this.setVisible(false);
         new Admin().setVisible(true);
        
         
        
    }//GEN-LAST:event_LogOutActionPerformed

    private void ReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReqActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new AdminRequests().setVisible(true);
        
        
    }//GEN-LAST:event_ReqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFunc().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBook;
    private javax.swing.JButton DeleteBook;
    private javax.swing.JLabel Hello;
    public javax.swing.JButton LogOut;
    private javax.swing.JLabel Please;
    private javax.swing.JButton Req;
    private javax.swing.JButton SwitchAdmin;
    // End of variables declaration//GEN-END:variables
}
