
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hamid
 */
public class DeleteBook extends javax.swing.JFrame {

    /**
     * Creates new form DeleteBook
     */
    public DeleteBook() {
        initComponents();
        initiatecategory();
        Name.setVisible(false);
        jComboBox2.setVisible(false);
        Delete.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        DeleteAnother = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        Category = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Next = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Main = new javax.swing.JButton();

        DeleteDialog.setMinimumSize(new java.awt.Dimension(400, 175));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Book Deleted Successfully!!");

        DeleteAnother.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DeleteAnother.setText("Delete Another Book");
        DeleteAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAnotherActionPerformed(evt);
            }
        });

        Return.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Return.setText("Return to Main Screen");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteDialogLayout = new javax.swing.GroupLayout(DeleteDialog.getContentPane());
        DeleteDialog.getContentPane().setLayout(DeleteDialogLayout);
        DeleteDialogLayout.setHorizontalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDialogLayout.createSequentialGroup()
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteDialogLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(DeleteAnother)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteDialogLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        DeleteDialogLayout.setVerticalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteAnother)
                    .addComponent(Return))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Book");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        Category.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Category.setText("Select the Section of the Book:");

        Name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Name.setText("Select the Book:");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        Next.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Delete.setForeground(new java.awt.Color(204, 0, 0));
        Delete.setText("Delete selected book");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Main.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Main.setText("Main Menu");
        Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Name)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Main)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Next))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(Delete)
                .addGap(18, 18, 18)
                .addComponent(Main)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        
        Next.setText("Change");
        jComboBox2.removeAllItems();
        String category;
        category= jComboBox1.getSelectedItem().toString();
        
        initiateBooks(category);
        Name.setVisible(true);
        Delete.setVisible(true);
        jComboBox2.setVisible(true);
    }//GEN-LAST:event_NextActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String book;
        
        book= jComboBox2.getSelectedItem().toString();
        
        try {
            DeleteBook(book);
        } catch (IOException ex) {
            Logger.getLogger(DeleteBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         DeleteDialog.setLocationRelativeTo(this);

        DeleteDialog.setVisible(true);
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void DeleteAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAnotherActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        DeleteDialog.dispose();
        new DeleteBook().setVisible(true);
    }//GEN-LAST:event_DeleteAnotherActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        DeleteDialog.dispose();
        new AdminFunc().setVisible(true);
    }//GEN-LAST:event_ReturnActionPerformed

    private void MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new AdminFunc().setVisible(true);
    }//GEN-LAST:event_MainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteBook().setVisible(true);
            }
        });
    }
    
     public void initiatecategory()
      {
          TreeNode objmain=new TreeNode("Categories");
          TreeNode obj1=new TreeNode("Fiction");
          TreeNode obj2=new TreeNode("Political");
          TreeNode obj3=new TreeNode("Biography");
          TreeNode obj4=new TreeNode("Science");
          TreeNode obj5=new TreeNode("Islamic");
          TreeNode obj6=new TreeNode("Magazines");
     
       
          BinaryTree tree=new BinaryTree(objmain);
          tree.root.a=obj1;
          tree.root.b=obj2;
          tree.root.c=obj3;
          tree.root.d=obj4;
          tree.root.e=obj5;
          tree.root.f=obj6;
          
          
          
            jComboBox1.addItem(tree.root.a.data);
            jComboBox1.addItem(tree.root.b.data);
            jComboBox1.addItem(tree.root.c.data); 
            jComboBox1.addItem(tree.root.d.data);
            jComboBox1.addItem(tree.root.e.data);
            jComboBox1.addItem(tree.root.f.data);
            
          
                  
          
      }
     
     public void initiateBooks(String Category)
     {
         
        BufferedReader buffer=null;
        try {
            File f=new File("E:\\3rd Semester\\DSA Lab\\Final_Project\\src\\Data.txt");
           BufferedReader br = new BufferedReader(new FileReader(f));
            Object[] lines=br.lines().toArray();
            String [] Unsorted=new String[100];
            String temp;
             String prevLine="";
             String prevprevline="";
             String prevprevprevline="";
             String prevprevprevprevline="";
               int count=0;
             for(int i=0; i<lines.length;i++)
            {
             
                String line = lines[i].toString();
                if (line.equals(Category))
                {
                   Unsorted[count]=prevprevprevprevline;
                   count++;
                }
                prevprevprevprevline=prevprevprevline;
                prevprevprevline=prevprevline;
                prevprevline=prevLine;
                prevLine=line;
            }
                for (int i = 0; i < count; i++) 
        {
            for (int j = i + 1; j < count; j++) { 
                if (Unsorted[i].compareTo(Unsorted[j])>0) 
                {
                    temp = Unsorted[i];
                    Unsorted[i] = Unsorted[j];
                    Unsorted[j] = temp;
                }
            }
        }
               
            for (int k=0; k<count; k++)
            {
                jComboBox2.addItem(Unsorted[k]);
            }
        } 
        
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(DeleteBook.class.getName()).log(Level.SEVERE, null, ex);
        } 
            
    }
     
     public void DeleteBook(String book) throws FileNotFoundException, IOException
     {
         StringBuilder sb = new StringBuilder();
    File f =new File("E:\\3rd Semester\\DSA Lab\\Final_Project\\src\\Data.txt");
    try (Scanner sc = new Scanner(f)) {
        String currentLine;
        while(sc.hasNext()){
            currentLine = sc.nextLine();
            if(currentLine.equals(book)){
               currentLine = sc.nextLine();
               currentLine=sc.nextLine();
               currentLine = sc.nextLine();
               currentLine = sc.nextLine();
               currentLine = sc.nextLine();
                continue;
//skips lineToRemove
            }
            sb.append(currentLine).append("\n");
        }
        
    }
   
    
    //Delete File Content
    PrintWriter pw = new PrintWriter(f);
    pw.close();

    BufferedWriter writer = new BufferedWriter(new FileWriter(f, true));
    writer.append(sb.toString());
    writer.close();
     }
     
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category;
    private javax.swing.JButton Delete;
    private javax.swing.JButton DeleteAnother;
    private javax.swing.JDialog DeleteDialog;
    private javax.swing.JButton Main;
    private javax.swing.JLabel Name;
    private javax.swing.JButton Next;
    private javax.swing.JButton Return;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
