
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hamid
 */
public class History extends javax.swing.JFrame {
  
    UserScreen us=new UserScreen();
    DLLOpt st=new DLLOpt();
    
    public static String [] BookNames=new String[15];
    
    public static DoublyNode navigate;
   
    
    /**
     * Creates new form History
     */
    public History(){
        initComponents();
        NoSelected.setVisible(false);
        NoItem.setVisible(false);
        try {
            setStack();
        } catch (IOException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
            navigate=st.set();
            Fill2();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Pop = new javax.swing.JButton();
        Main = new javax.swing.JButton();
        NoItem = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        Selected = new javax.swing.JButton();
        NoSelected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("History");

        jList1.setBackground(new java.awt.Color(204, 255, 204));
        jList1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(102, 0, 153));
        jScrollPane1.setViewportView(jList1);

        Pop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Pop.setForeground(new java.awt.Color(204, 0, 0));
        Pop.setText("Delete 1st Item");
        Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopActionPerformed(evt);
            }
        });

        Main.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Main.setText("Main Menu");
        Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainActionPerformed(evt);
            }
        });

        NoItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NoItem.setForeground(new java.awt.Color(204, 0, 0));
        NoItem.setText("No Item in History");

        Clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Clear.setForeground(new java.awt.Color(204, 0, 0));
        Clear.setText("Clear All");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Selected.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Selected.setForeground(new java.awt.Color(204, 0, 0));
        Selected.setText("Delete selected Item");
        Selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedActionPerformed(evt);
            }
        });

        NoSelected.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        NoSelected.setForeground(new java.awt.Color(204, 0, 0));
        NoSelected.setText("No Item selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(Pop)
                .addGap(49, 49, 49)
                .addComponent(Selected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(Clear)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Main))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(NoItem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(NoSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(NoSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NoItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear)
                    .addComponent(Pop)
                    .addComponent(Selected))
                .addGap(31, 31, 31)
                .addComponent(Main)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopActionPerformed
        
         NoSelected.setVisible(false);
        try {
            
            delete(st.head.name);
        } catch (IOException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        }
           st.DeleteatFirst();
        Fill2();
    }//GEN-LAST:event_PopActionPerformed

    private void MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_MainActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        
        NoSelected.setVisible(false);
        
        DefaultListModel listModel = (DefaultListModel) jList1.getModel();
        try {
            clearTheFile();
        } catch (IOException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        }
            NoItem.setVisible(true);
            Pop.setVisible(false);
            Selected.setVisible(false);
            Clear.setVisible(false);
          jList1.setVisible(false);
          Fill2();
    }//GEN-LAST:event_ClearActionPerformed

    private void SelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedActionPerformed
        // TODO add your handling code here:
        
         NoSelected.setVisible(false);
         
        int n;
        String name="";
       try{ 
        n=jList1.getSelectedIndex();
        name=BookNames[n];
       }
       catch (Exception e)
       {
            NoSelected.setVisible(true);
            return;
       }
        
        
        try {
            delete(name);
        } catch (IOException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        }
        st.Delete(name);
        if(st.isEmpty())
        {
            try {
                clearTheFile();
            } catch (IOException ex) {
                Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Fill2();
        
    }//GEN-LAST:event_SelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }
    public void setStack() throws IOException
    {
        String book,author;
         File fr =new File(us.Path);
         BufferedReader buffer;
           buffer = new BufferedReader(new FileReader(fr));
          String line=buffer.readLine();
            
                while(line!=null)
                {
                    if(line.equals("*****"))
                    {
                        break;
                    }
                    book=line;
                    line=buffer.readLine();
                    author=line;
                    line=buffer.readLine();
                    st.insertFirst(book, author);
                  
                }
                buffer.close();
    }
    
    public static void clearTheFile() throws IOException
    {
        File f=new File(UserScreen.Path);
     PrintWriter wr =new PrintWriter(new FileWriter(f, false));
       BufferedWriter bw =new BufferedWriter(wr);      
       
          bw.close();
    }
    
    
    
      public void Fill2()
    {
        DefaultListModel add=new DefaultListModel();  
          
        if (st.isEmpty())
        {
                NoItem.setVisible(true);
                Pop.setVisible(false);
             
                  int countNo=1;
              
                  jList1.setVisible(false);
                  Clear.setVisible(false);
                  Selected.setVisible(false);
              
               
        }
        
        else
        {
            navigate=st.set();
        
               int countNo=1;
               int StringNo=0;
               
              
              
                while(navigate!=null)
                {
                add.addElement(countNo+". "+navigate.name+" - by - "+ navigate.author);
                jList1.setModel(add);
                BookNames[StringNo]=navigate.name;
                navigate=st.moveForward(navigate);
             
                countNo=countNo+1;
                StringNo=StringNo+1;
                }
        }
                   
            }
      
      public void delete(String name) throws FileNotFoundException, IOException
      {
         StringBuilder sb = new StringBuilder();
    File f =new File(us.Path);
    try (Scanner sc = new Scanner(f)) {
        String currentLine;
        while(sc.hasNext()){
            currentLine = sc.nextLine();
            if(currentLine.equals(name)){
               currentLine = sc.nextLine();
                continue;
//skips lineToRemove
            }
            sb.append(currentLine).append("\n");
        }
        
    }
   
    
    //Delete File Content
    PrintWriter pw = new PrintWriter(f);
    pw.close();

    BufferedWriter writer = new BufferedWriter(new FileWriter(f, true));
    writer.append(sb.toString());
    writer.close();
      }
           
        
       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Main;
    private javax.swing.JLabel NoItem;
    private javax.swing.JLabel NoSelected;
    private javax.swing.JButton Pop;
    private javax.swing.JButton Selected;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
