/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hamid
 */

import java.io.BufferedWriter;
import java.nio.file.*;

import java.io.IOException;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MainScreen extends javax.swing.JFrame {
    String path;
  Hash hs=new Hash(20);
  public static String userName;
    /**
     * Creates new form Main
     */
    public MainScreen() {
        initComponents();
        insertion();
     
        
        ErrorUser.setVisible(false);
        PinError.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        adminLink = new javax.swing.JLabel();
        ErrorMessage = new javax.swing.JLabel();
        ErrorUser = new javax.swing.JLabel();
        PinError = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        PinField = new javax.swing.JPasswordField();
        Please = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Screen");
        setMinimumSize(new java.awt.Dimension(704, 361));

        Name1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Name1.setText("Enter Your Name:");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Password.setText("Enter Your Pin:");

        adminLink.setBackground(new java.awt.Color(0, 0, 0));
        adminLink.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adminLink.setForeground(new java.awt.Color(0, 102, 255));
        adminLink.setText("I'm an Admin");
        adminLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLinkMouseClicked(evt);
            }
        });

        ErrorMessage.setForeground(new java.awt.Color(204, 0, 0));

        ErrorUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ErrorUser.setForeground(new java.awt.Color(204, 0, 0));
        ErrorUser.setText("**This name does not exist");

        PinError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PinError.setForeground(new java.awt.Color(204, 0, 0));
        PinError.setText("**Wrong Pin");

        Submit.setText("Log in");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        PinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinFieldActionPerformed(evt);
            }
        });

        Please.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Please.setText("Please Login to Continue");

        Welcome.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(102, 102, 0));
        Welcome.setText("Welcome!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ErrorUser)
                            .addComponent(PinError, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(Submit))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Password)
                                    .addGap(49, 49, 49)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NameField)
                                .addComponent(PinField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Please, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminLink, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ErrorMessage)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Welcome)
                        .addGap(27, 27, 27)
                        .addComponent(Please, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ErrorUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PinError)
                        .addGap(34, 34, 34)))
                .addComponent(adminLink)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void adminLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLinkMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        new Admin().setVisible(true);
        
    }//GEN-LAST:event_adminLinkMouseClicked

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        
        ErrorUser.setVisible(false);
        PinError.setVisible(false);
        
        String name;
        int pin=0;
        
        name = this.NameField.getText();
          String pinno=this.PinField.getText();
        try{
          
        pin = Integer.parseInt(this.PinField.getText());
        
        
        }
        catch(Exception e)
        {
                PinError.setVisible(false);
                PinField.setText(null);
        }
        
        if(this.NameField.getText()== null || this.PinField.getText()==null)
        {
            ErrorUser.setText("Please Enter all credentials");
             ErrorUser.setVisible(true);
        }
        if(hs.SearchName(name))
        {
            if (hs.SearchPin(name,pin))
            {
                userName=name;
                this.setVisible(false);
                new UserScreen().setVisible(true);
            }
            else
            {
                PinError.setVisible(true);
                PinField.setText(null);
            }
        }
        else
        {
              ErrorUser.setVisible(true);
              PinField.setText(null);
        }
            if(name==null || pinno ==null)
        {
            ErrorUser.setText("Please Enter all credentials");
             ErrorUser.setVisible(true);
             PinError.setVisible(false);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void PinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
      
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }
    
      public void insertion ()
    {
        String names[]={"Hamid Faraz","Junaid Abbas","Abshaar Hassan","Kashif Ali","Saad Mubeen","Furqan Fiaz","Joun Ahmed","Shariq Bin Shahid","Hassan Rahim","Affan Ahmed","Michael Corleone","Tony Montana","Luca Brasi","Ted Kramer","Lt. Dan","Al Pacino","Dustin Hoffman","Tom Hanks","Robert De Niro","Travis Bickle"};
        int pins[]={2345,9023,8612,9803,2175,7922,2052,1098,3521,9761,1022,3217,8252,9122,9067,1992,5321,8100,2317,1212};
        
        for (int i=0; i<names.length;i++)
        {
              hs.insert(pins[i],names[i]);
        }
        
    }
      
          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JLabel ErrorUser;
    private javax.swing.JLabel Name1;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel PinError;
    private javax.swing.JPasswordField PinField;
    private javax.swing.JLabel Please;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel adminLink;
    // End of variables declaration//GEN-END:variables
}
