/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hamid
 */
import java.io.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SearchByName extends javax.swing.JFrame {
    
    UserScreen us= new UserScreen();
    SavedData sd=new SavedData();

   
    /**
     * Creates new form SearchByName
     */
    public SearchByName() {
        initComponents();
        ErrorBook.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        BookAns4 = new javax.swing.JLabel();
        BookAns6 = new javax.swing.JLabel();
        BookNameInput = new javax.swing.JLabel();
        BookNameField = new javax.swing.JTextField();
        BookName = new javax.swing.JLabel();
        AuthorName = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        BookName3 = new javax.swing.JLabel();
        BookName4 = new javax.swing.JLabel();
        NameAns = new javax.swing.JLabel();
        AuthorAns = new javax.swing.JLabel();
        YearAns = new javax.swing.JLabel();
        CatAns = new javax.swing.JLabel();
        RackAns = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        ErrorBook = new javax.swing.JLabel();
        BookAns1 = new javax.swing.JLabel();
        AuthorAns1 = new javax.swing.JLabel();
        YearAns1 = new javax.swing.JLabel();
        CatAns1 = new javax.swing.JLabel();
        RackAns1 = new javax.swing.JLabel();
        Main = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("jLabel1");

        BookAns4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BookAns4.setText("                                           ");
        BookAns4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BookAns6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BookAns6.setText("                                           ");
        BookAns6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search by Name");

        BookNameInput.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BookNameInput.setText("Enter Book Name:");

        BookNameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BookNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BookNameFieldKeyReleased(evt);
            }
        });

        BookName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BookName.setText("Book:");

        AuthorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AuthorName.setText("Author Name:");

        Year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Year.setText("Year Published:");

        BookName3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BookName3.setText("Section:");

        BookName4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BookName4.setText("Rack:");

        NameAns.setBackground(new java.awt.Color(255, 255, 255));
        NameAns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        AuthorAns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        YearAns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        CatAns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        RackAns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        ErrorBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ErrorBook.setForeground(new java.awt.Color(204, 0, 0));
        ErrorBook.setText("No Book found!!");

        BookAns1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BookAns1.setForeground(new java.awt.Color(0, 0, 102));
        BookAns1.setText("                                           ");

        AuthorAns1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AuthorAns1.setForeground(new java.awt.Color(0, 0, 102));
        AuthorAns1.setText("                                           ");

        YearAns1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        YearAns1.setForeground(new java.awt.Color(0, 0, 102));
        YearAns1.setText("                                           ");

        CatAns1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CatAns1.setForeground(new java.awt.Color(0, 0, 102));
        CatAns1.setText("                                           ");

        RackAns1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RackAns1.setForeground(new java.awt.Color(0, 0, 102));
        RackAns1.setText("                                           ");

        Main.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Main.setText("Main Menu");
        Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ErrorBook)
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AuthorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BookName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addComponent(BookName3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookName4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AuthorAns, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(YearAns, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameAns, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(YearAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CatAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RackAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AuthorAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(BookNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RackAns, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CatAns, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Main)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookNameInput)
                    .addComponent(BookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addGap(18, 18, 18)
                .addComponent(ErrorBook, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookName)
                    .addComponent(NameAns)
                    .addComponent(BookAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthorName)
                    .addComponent(AuthorAns)
                    .addComponent(AuthorAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Year)
                    .addComponent(YearAns)
                    .addComponent(YearAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookName3)
                    .addComponent(CatAns)
                    .addComponent(CatAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookName4)
                    .addComponent(RackAns)
                    .addComponent(RackAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Main)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
      
        try {
            search();
        } catch (IOException ex) {
            Logger.getLogger(SearchByName.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SearchActionPerformed

    private void MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_MainActionPerformed

    private void BookNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BookNameFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BookNameFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchByName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchByName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchByName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchByName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchByName().setVisible(true);
            }
        });
    }
    
    public void search() throws FileNotFoundException, IOException
    {
        
           // TODO add your handling code here:
            ErrorBook.setVisible(false);
            
            BookAns1.setText(null);
            AuthorAns1.setText(null);
            YearAns1.setText(null);
            CatAns1.setText(null);
            RackAns1.setText(null);
            
            String nameSend;
            String AuthSend;
            
            String name;
            name = this.BookNameField.getText();
            boolean found=false;
            File fr =new File("E:\\3rd Semester\\DSA Lab\\Final_Project\\src\\Data.txt");
            BufferedReader buffer;
            
            buffer = new BufferedReader(new FileReader(fr));
            String line=buffer.readLine();
            
            
            while(line!=null)
            {
                  if (line.equalsIgnoreCase(name))
                  {
                     String thisLine=line; 
                     line= buffer.readLine();
                     if(line.equals("///"))
                     {
                      found=true;
                      BookAns1.setText(thisLine);
                      nameSend=thisLine;
                      line=buffer.readLine();
                      AuthorAns1.setText(line);
                      AuthSend=line;
                      line=buffer.readLine();
                      YearAns1.setText(line);
                      line=buffer.readLine();
                      CatAns1.setText(line);
                      line=buffer.readLine();
                      RackAns1.setText(line);
                      line=buffer.readLine();
                      
                      
                       if(sd.who==false)
                      {
                        addtoStack(nameSend, AuthSend);
                      }
                       
                     }
                   
                  }
                  line=buffer.readLine();
            }
            
            if (found==false)
            {
                 ErrorBook.setVisible(true);
            }
                
              
    
    }
    
     public void addtoStack(String name, String auth) throws FileNotFoundException, IOException
    {
          StringBuilder sb = new StringBuilder();
    File f =new File(us.Path);
    try (Scanner sc = new Scanner(f)) {
        String currentLine;
        while(sc.hasNext()){
            currentLine = sc.nextLine();
            if(currentLine.equals("*****")){
              
                break;
//skips lineToRemove
            }
            sb.append(currentLine).append("\n");
        }
    }
    //Delete File Content
    PrintWriter pw = new PrintWriter(f);
    pw.close();

    BufferedWriter writer = new BufferedWriter(new FileWriter(f, true));
    writer.append(sb.toString());
    writer.close();
    
    WriteNow(name,auth);
    }
     
     
    
      public void WriteNow(String name, String author) throws IOException
    {
          
      File f=new File(us.Path);
     PrintWriter wr =new PrintWriter(new FileWriter(f, true));
       BufferedWriter bw =new BufferedWriter(wr);      
            
    
     bw.write(name);
     bw.newLine();
     bw.write(author);
      bw.newLine();
     bw.write("*****");
     bw.close();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorAns;
    private javax.swing.JLabel AuthorAns1;
    private javax.swing.JLabel AuthorName;
    private javax.swing.JLabel BookAns1;
    private javax.swing.JLabel BookAns4;
    private javax.swing.JLabel BookAns6;
    private javax.swing.JLabel BookName;
    private javax.swing.JLabel BookName3;
    private javax.swing.JLabel BookName4;
    private javax.swing.JTextField BookNameField;
    private javax.swing.JLabel BookNameInput;
    private javax.swing.JLabel CatAns;
    private javax.swing.JLabel CatAns1;
    private javax.swing.JLabel ErrorBook;
    private javax.swing.JButton Main;
    private javax.swing.JLabel NameAns;
    private javax.swing.JLabel RackAns;
    private javax.swing.JLabel RackAns1;
    private javax.swing.JButton Search;
    private javax.swing.JLabel Year;
    private javax.swing.JLabel YearAns;
    private javax.swing.JLabel YearAns1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
