
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hamid
 */
public class UserScreen extends javax.swing.JFrame {
    
  
     static String Path;
    static File tempFile;
    
    static int count=0;
    

   SavedData sd=new SavedData();
    /**
     * Creates new form UserScreen
     */
    public UserScreen() {
        initComponents();
        count=count+1;
        if(sd.who==true)
        {
            Request.setVisible(false);
            Switch.setVisible(true);
            Hello.setText("Hello "+sd.nameAdmin);
            LogOut.setVisible(false);
            History.setVisible(false);
        }
        else
        {
            Request.setVisible(true);
            Switch.setVisible(false);
            Hello.setText("Hello "+sd.userName);
            LogOut.setVisible(true);
            
            if(count==1)
            {
                 try {
          tempfile();
      } catch (IOException ex) {
          Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
      }
            }
            
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        byName = new javax.swing.JButton();
        byCategory = new javax.swing.JButton();
        Request = new javax.swing.JButton();
        Switch = new javax.swing.JButton();
        Please = new javax.swing.JLabel();
        Hello = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        History = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Screen");

        byName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        byName.setText("Search by Book name");
        byName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        byName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byNameActionPerformed(evt);
            }
        });

        byCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        byCategory.setText("Search by Book Category");
        byCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        byCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byCategoryActionPerformed(evt);
            }
        });

        Request.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Request.setText("Request a new book");
        Request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestActionPerformed(evt);
            }
        });

        Switch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Switch.setText("Switch back to Admin");
        Switch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitchActionPerformed(evt);
            }
        });

        Please.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        Please.setText("Select Any option");

        Hello.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Hello.setForeground(new java.awt.Color(153, 0, 153));
        Hello.setText("    ");
        Hello.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LogOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 0, 0));
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        History.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        History.setText("Check History");
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(byCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(byName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(Please, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Hello, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                            .addComponent(Switch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(History)
                        .addGap(98, 98, 98)
                        .addComponent(Request, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(Hello)
                .addGap(18, 18, 18)
                .addComponent(Please, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(byName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(byCategory)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Request)
                    .addComponent(LogOut)
                    .addComponent(History))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Switch)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void byNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byNameActionPerformed
        // TODO add your handling code here:
        
                this.setVisible(false);
                new SearchByName().setVisible(true);
    }//GEN-LAST:event_byNameActionPerformed

    private void SwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitchActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new AdminFunc().setVisible(true);
    }//GEN-LAST:event_SwitchActionPerformed

    private void byCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byCategoryActionPerformed
        // TODO add your handling code here:
        
                this.setVisible(false);
                new SearchByCategory().setVisible(true);
    }//GEN-LAST:event_byCategoryActionPerformed

    private void RequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
                new UserRequests().setVisible(true);
    }//GEN-LAST:event_RequestActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        
        count=0;
        tempFile.delete();
        this.setVisible(false);
        new MainScreen().setVisible(true);

    }//GEN-LAST:event_LogOutActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
        new History().setVisible(true);
    }//GEN-LAST:event_HistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserScreen().setVisible(true);
            }
        });
    }
    
      public void tempfile() throws IOException
      {
             File directoryPath = new File("E:/3rd Semester/DSA Lab/Final_Project/src");
           
            // Create a temporary file in the specified directory.
            tempFile = File.createTempFile("temp", ".txt", directoryPath);
              Path = tempFile.toString();
           
           tempFile.deleteOnExit();
           
           
      }

    
     
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hello;
    public javax.swing.JButton History;
    public javax.swing.JButton LogOut;
    private javax.swing.JLabel Please;
    private javax.swing.JButton Request;
    private javax.swing.JButton Switch;
    private javax.swing.JButton byCategory;
    private javax.swing.JButton byName;
    // End of variables declaration//GEN-END:variables
}
